# Generated by Django 4.2 on 2023-05-16 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateField(verbose_name='Начало')),
                ('dateFinish', models.DateField(verbose_name='Конец')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Даты',
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('launch', models.CharField(choices=[('KICKSTARTER', 'Кикстартер'), ('ELECTRIC', 'Электрический')], max_length=255, verbose_name='Тип запуска')),
                ('seatHeight', models.FloatField(verbose_name='Высота сиденья')),
                ('tankCapacity', models.FloatField(verbose_name='Емкость топливного бака')),
                ('engineCapacity', models.IntegerField(verbose_name='Объем двигателя')),
                ('enginePower', models.FloatField(verbose_name='Мощность двигателя')),
                ('image', models.ImageField(blank=True, upload_to='images/moto')),
                ('description', models.TextField(default=None, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Мотоцикл',
                'verbose_name_plural': 'Мотоциклы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('duration', models.IntegerField(default=None, verbose_name='Длительность')),
                ('length', models.IntegerField(default=None, verbose_name='Протяженность маршрута')),
                ('lvl', models.CharField(choices=[('EASY', 'Начальный'), ('MEDIUM', 'Средний'), ('DIFFICULT', 'Сложный')], default=None, max_length=255, verbose_name='Уровень сложности')),
                ('priceWOMoto', models.IntegerField(default=None, verbose_name='Цена на воем мотоцикле')),
                ('priceWMoto', models.IntegerField(default=None, verbose_name='Цена с арендтой мотоцикла')),
                ('type', models.CharField(choices=[('WEEKEND', 'Маршруты выходного дня'), ('LONG', 'Многодневные маршруты')], default=None, max_length=255, verbose_name='Тип путешествия')),
                ('image', models.ImageField(blank=True, upload_to='images/trip')),
                ('date', models.ManyToManyField(default=None, to='base.dates', verbose_name='Даты')),
            ],
            options={
                'verbose_name': 'Путешествие',
                'verbose_name_plural': 'Путешествия',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(verbose_name='Вего мест')),
                ('booked', models.IntegerField(default=0, verbose_name='Занято мест')),
                ('dateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dates', verbose_name='Дата тура')),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trip', verbose_name='Путешествие')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('isRentMoto', models.BooleanField(default=True, verbose_name='Аренда')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время бронирования')),
                ('moreInfo', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('motoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.moto', verbose_name='Мотоцикл')),
                ('tourId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tour', verbose_name='Тур')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
