# Generated by Django 4.2 on 2023-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
