# Generated by Django 4.2 on 2023-05-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_dates_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='deleted',
        ),
    ]
