# Generated by Django 4.2.7 on 2024-02-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_dates_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='places',
            field=models.TextField(default=None, null=True, verbose_name='Промежуточные точки'),
        ),
    ]
