# Generated by Django 4.2.7 on 2024-02-17 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_trip_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='rentPrice',
            field=models.IntegerField(default=10000, verbose_name='Цена аренды'),
        ),
        migrations.CreateModel(
            name='MotoReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время бронирования')),
                ('days', models.IntegerField(verbose_name='Дни')),
                ('moreInfo', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('motoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.moto', verbose_name='Мотоцикл')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
