# Generated by Django 4.2.7 on 2024-03-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_moto_rentprice_motoreservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motoreservation',
            options={'verbose_name': 'Бронь мотоцикла', 'verbose_name_plural': 'Бронь мотоциклов'},
        ),
        migrations.CreateModel(
            name='ToursStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Кол-во посещений')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Время перехода')),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trip', verbose_name='Путешествие')),
            ],
            options={
                'verbose_name': 'Статистика тура',
                'verbose_name_plural': 'Статистика туров',
            },
        ),
    ]
