# Generated by Django 4.2.7 on 2024-05-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_motoreservation_options_toursstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoreservation',
            name='day',
            field=models.DateField(default=None, verbose_name='День старта аренды'),
        ),
    ]
