# Generated by Django 4.2.7 on 2024-05-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_motoreservation_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoreservation',
            name='isPaid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
